[lsp]
pubkey = "022814b30dc90b3c53312c250021165644fdf1650aa7ba4be5d6cd51302b2f31bb"
address = "127.0.0.1:9737"
auth = "00000000000000000000000000000000"

[node]
network = "signet"
chain_source_url = "https://mutinynet.com/api/"
data_dir = "data"  # Changed from .stable-channels to data
alias = "user"
port = 9736

[stable_channel_defaults]
expected_usd = 20.0
sc_dir = "data"