#!/bin/sh
# nginx docker-entrypoint.d hook: once sc-lsp has generated its API key
# (<storage_dir>/<network>/api_key, raw bytes), make it available hex-encoded at
# /setup so the user can copy it into the GUI connection screen without SSH.
# The sc-lsp storage dir is mounted read-only at /run/sc-lsp; behind Umbrel's
# app_proxy the page is gated by the user's Umbrel login.

write_setup_allowlist() {
    allow_file=/etc/nginx/setup-key-allow.conf
    tmp="${allow_file}.tmp"
    hosts="${SC_SETUP_KEY_ALLOW_HOSTS:-stable-channels-lsp_app_proxy_1 app_proxy}"

    resolve_host() {
        if command -v getent >/dev/null 2>&1; then
            getent hosts "$1" 2>/dev/null | awk '{print $1}'
        elif command -v nslookup >/dev/null 2>&1; then
            nslookup "$1" 2>/dev/null | awk '
                /^Address [0-9]+: / {print $3}
                /^Address: / && $2 !~ /:53$/ {print $2}
            '
        fi
    }

    {
        printf '# Generated by 40-provision-gui-api-key.sh.\n'
        for cidr in ${SC_SETUP_KEY_ALLOW_CIDRS:-}; do
            printf 'allow %s;\n' "$cidr"
        done
        for host in $hosts; do
            resolve_host "$host" | while read -r ip; do
                [ -n "$ip" ] && printf 'allow %s;\n' "$ip"
            done
        done
        printf 'deny all;\n'
    } | awk '!seen[$0]++' > "$tmp"

    mv -f "$tmp" "$allow_file"
}

find_api_key() {
    preferred="${SC_NETWORK:-}"
    if [ -z "$preferred" ] && [ -s /run/sc-lsp/network ]; then
        preferred="$(sed -n '1p' /run/sc-lsp/network 2>/dev/null || true)"
    fi
    if [ -n "$preferred" ] && [ -s "/run/sc-lsp/${preferred}/api_key" ]; then
        printf '%s\n' "/run/sc-lsp/${preferred}/api_key"
        return 0
    fi
    if [ -s /run/sc-lsp/bitcoin/api_key ]; then
        printf '%s\n' /run/sc-lsp/bitcoin/api_key
        return 0
    fi
    for candidate in /run/sc-lsp/*/api_key; do
        [ -s "$candidate" ] || continue
        printf '%s\n' "$candidate"
        return 0
    done
    return 1
}

write_setup_allowlist

(
    until key_file="$(find_api_key)"; do sleep 5; done
    hex="$(od -An -tx1 "$key_file" | tr -d ' \n')"
    mkdir -p /usr/share/nginx/html/setup
    # Bare key for the GUI's zero-input auto-connect (fetched same-origin).
    # Umbrel's app proxy protects both files with the operator's login.
    printf '%s\n' "$hex" > /usr/share/nginx/html/setup/key.txt.tmp
    cat > /usr/share/nginx/html/setup/index.html.tmp <<EOF
<!doctype html><meta charset="utf-8"><title>Stable Channels LSP — Setup</title>
<body style="font-family:system-ui;max-width:40em;margin:4em auto">
<h2>Operator access</h2>
<p>The dashboard connects automatically. This API key grants administrative access to the LSP; keep it private and never share it with wallet users.</p>
<pre style="background:#eee;padding:1em;word-break:break-all;white-space:pre-wrap">$hex</pre>
<p><a href="/">Open the GUI</a></p>
</body>
EOF
    mv -f /usr/share/nginx/html/setup/key.txt.tmp /usr/share/nginx/html/setup/key.txt
    mv -f /usr/share/nginx/html/setup/index.html.tmp /usr/share/nginx/html/setup/index.html
) &
